#!/usr/bin/env python3

# this file is for the trace NFA
#Team: Makenna Gall (team of 1)

import time
import sys
def main():
    filename = sys.argv[1]
    readIn(filename)



#run main:
if __name__ == "__main__":
    main()
